import { examesClinicos as nomes } from '@/lib/examesClinicos';

const descricoes = {
  'Amilase': 'Mede uma enzima relacionada principalmente ao pâncreas e às glândulas salivares.',
  'Anti-HBc IgG': 'Pesquisa anticorpos que ajudam a identificar contato anterior com o vírus da hepatite B.',
  'Anti-HBc IgM': 'Pesquisa anticorpos que podem estar associados à fase recente da hepatite B.',
  'Anti-HBs': 'Avalia anticorpos frequentemente usados para verificar imunidade contra a hepatite B.',
  'ASLO': 'Auxilia na investigação de infecção recente por bactérias estreptocócicas.',
  'Bacterioscopia de orofaringe': 'Analisa material da garganta para auxiliar na investigação de infecções bacterianas.',
  'Bacterioscopia vaginal, perianal ou uretral': 'Analisa secreções da região coletada em busca de bactérias e sinais de infecção.',
  'Beta-hCG quantitativo': 'Mede o hormônio hCG e é usado principalmente na confirmação e no acompanhamento inicial da gestação.',
  'Bilirrubinas': 'Auxilia na avaliação do fígado, das vias biliares e da renovação das hemácias.',
  'Cálcio': 'Auxilia na avaliação do metabolismo mineral, ossos, rins e paratireoides.',
  'Citologia cervical oncótica': 'Examina células do colo do útero para rastrear alterações e lesões precursoras.',
  'CK e CK-MB': 'Mede enzimas musculares; a CK-MB pode integrar a avaliação de lesão do músculo cardíaco.',
  'Coagulograma': 'Reúne testes que avaliam a coagulação e auxiliam na investigação de sangramentos.',
  'Colesterol total e frações': 'Avalia gorduras do sangue relacionadas ao risco cardiovascular.',
  'Coombs direto': 'Investiga anticorpos aderidos às hemácias e auxilia na avaliação de algumas anemias hemolíticas.',
  'Coombs indireto': 'Pesquisa anticorpos contra hemácias e é usado em avaliações transfusionais e gestacionais.',
  'Creatinina': 'Auxilia na avaliação da função dos rins e no cálculo da filtração renal estimada.',
  'EAS (urina tipo 1)': 'Analisa aspectos físicos, químicos e microscópicos da urina.',
  'Espermograma': 'Avalia quantidade, movimentação e características dos espermatozoides.',
  'Estradiol': 'Auxilia na avaliação da função ovariana, ciclo menstrual e condições hormonais.',
  'Fator reumatoide (FR)': 'Pesquisa um autoanticorpo que pode auxiliar na investigação de doenças autoimunes.',
  'Ferritina': 'Avalia as reservas de ferro do organismo.',
  'Ferro': 'Mede o ferro circulante e integra a investigação de anemias e alterações do metabolismo do ferro.',
  'Fosfatase alcalina': 'Avalia uma enzima relacionada principalmente ao fígado, às vias biliares e aos ossos.',
  'Fósforo': 'Mede um mineral importante para ossos, músculos e produção de energia.',
  'FSH': 'Auxilia na avaliação da função ovariana ou testicular, puberdade e fertilidade.',
  'GGT': 'Avalia uma enzima associada ao fígado e às vias biliares.',
  'Glicose': 'Mede o açúcar no sangue e auxilia no rastreamento e acompanhamento de alterações glicêmicas.',
  'HBsAg': 'Pesquisa um antígeno do vírus da hepatite B e auxilia na identificação de infecção atual.',
  'HCV': 'Pesquisa anticorpos contra o vírus da hepatite C; resultados reagentes podem exigir confirmação.',
  'HDL': 'Mede uma fração do colesterol e integra a avaliação do risco cardiovascular.',
  'Hemoglobina glicada': 'Estima a média da glicose dos últimos meses.',
  'Hemograma': 'Avalia hemácias, leucócitos e plaquetas, auxiliando na investigação de anemias e infecções.',
  'HIV': 'Pesquisa marcadores da infecção pelo HIV; método e janela diagnóstica influenciam a interpretação.',
  'LDH': 'Mede uma enzima presente em vários tecidos e pode indicar lesão celular.',
  'LDL': 'Mede uma fração do colesterol usada na avaliação e no acompanhamento do risco cardiovascular.',
  'LH': 'Auxilia na avaliação da ovulação, fertilidade e função ovariana ou testicular.',
  'Magnésio': 'Mede um mineral importante para músculos, nervos, coração e metabolismo.',
  'MIF': 'Método utilizado na conservação e análise de fezes para pesquisa de parasitas.',
  'Parasitológico de fezes': 'Pesquisa elementos relacionados a parasitoses intestinais.',
  'PCR': 'Mede a proteína C-reativa, um marcador de inflamação que não aponta isoladamente a causa.',
  'Pesquisa de gorduras fecais': 'Auxilia na investigação de má absorção e alterações digestivas.',
  'Pesquisa de plasmódio': 'Pesquisa no sangue o parasita causador da malária.',
  'Pesquisa de sangue oculto': 'Detecta pequenas quantidades de sangue não visíveis nas fezes.',
  'Plaquetas': 'Conta células importantes para a coagulação e o controle de sangramentos.',
  'Potássio': 'Mede um eletrólito essencial ao funcionamento muscular e cardíaco.',
  'Progesterona': 'Auxilia na avaliação da ovulação, ciclo menstrual e gestação.',
  'Prolactina': 'Auxilia na investigação de alterações menstruais, produção de leite e função hormonal.',
  'Proteínas totais e frações': 'Avalia proteínas do sangue e auxilia na investigação nutricional, hepática e renal.',
  'PSA livre': 'Complementa a avaliação da próstata quando interpretado com o PSA total.',
  'PSA total': 'Auxilia na avaliação da próstata, mas não confirma câncer isoladamente.',
  'Reticulócitos': 'Conta hemácias jovens e ajuda a avaliar a produção de células vermelhas pela medula.',
  'Rubéola IgG': 'Pesquisa anticorpos geralmente relacionados à imunidade ou contato anterior com rubéola.',
  'Rubéola IgM': 'Pesquisa anticorpos que podem estar associados à infecção recente por rubéola.',
  'SHBG': 'Mede a proteína que transporta hormônios sexuais e auxilia na interpretação hormonal.',
  'Sódio': 'Mede um eletrólito essencial ao equilíbrio de líquidos, nervos e músculos.',
  'T3': 'Mede um hormônio que pode complementar a avaliação da tireoide.',
  'T4': 'Mede a tiroxina total e auxilia na avaliação da função tireoidiana.',
  'T4 livre': 'Mede a fração livre da tiroxina e costuma ser interpretado junto ao TSH.',
  'Testosterona livre': 'Avalia a fração biologicamente disponível da testosterona.',
  'TGO': 'Mede a enzima AST/TGO, presente no fígado e em outros tecidos.',
  'TGP': 'Mede a enzima ALT/TGP, relacionada principalmente ao fígado.',
  'Tipagem sanguínea': 'Identifica o grupo ABO e o fator Rh.',
  'Toxoplasmose IgG': 'Pesquisa anticorpos relacionados a contato anterior com o parasita da toxoplasmose.',
  'Toxoplasmose IgM': 'Pesquisa anticorpos que podem sugerir infecção recente por toxoplasmose.',
  'Triglicerídeos': 'Mede um tipo de gordura do sangue e integra a avaliação metabólica e cardiovascular.',
  'TSH': 'Mede o hormônio que regula a tireoide e é um dos principais testes de sua função.',
  'Ureia': 'Mede um produto do metabolismo das proteínas e auxilia na avaliação renal.',
  'VLDL': 'Avalia uma fração de lipoproteínas relacionada ao transporte de triglicerídeos.',
};

export const examesClinicosDetalhados = nomes.map((nome) => ({
  nome,
  descricao: descricoes[nome] || 'Exame laboratorial utilizado como apoio à avaliação clínica conforme indicação profissional.',
}));
