export const examesClinicos = [
  'Amilase', 'Anti-HBc IgG', 'Anti-HBc IgM', 'Anti-HBs', 'ASLO',
  'Bacterioscopia de orofaringe', 'Bacterioscopia vaginal, perianal ou uretral',
  'Beta-hCG quantitativo', 'Bilirrubinas', 'Cálcio', 'Citologia cervical oncótica',
  'CK e CK-MB', 'Coagulograma', 'Colesterol total e frações', 'Coombs direto',
  'Coombs indireto', 'Creatinina', 'EAS (urina tipo 1)', 'Espermograma', 'Estradiol',
  'Ferritina', 'Ferro', 'Fosfatase alcalina', 'Fósforo', 'Fator reumatoide (FR)',
  'FSH', 'GGT', 'Glicose', 'HBsAg', 'HCV', 'HDL', 'Hemoglobina glicada',
  'Hemograma', 'HIV', 'LDH', 'LDL', 'LH', 'Magnésio', 'MIF',
  'Parasitológico de fezes', 'PCR', 'Pesquisa de gorduras fecais',
  'Pesquisa de plasmódio', 'Pesquisa de sangue oculto', 'Plaquetas', 'Potássio',
  'Progesterona', 'Prolactina', 'Proteínas totais e frações', 'PSA livre',
  'PSA total', 'Reticulócitos', 'Rubéola IgG', 'Rubéola IgM', 'SHBG', 'Sódio',
  'T3', 'T4', 'T4 livre', 'Testosterona livre', 'TGO', 'TGP', 'Tipagem sanguínea',
  'Toxoplasmose IgG', 'Toxoplasmose IgM', 'Triglicerídeos', 'TSH', 'Ureia', 'VLDL',
].sort((a, b) => a.localeCompare(b, 'pt-BR'));
